hosts:
    - starz0r.com

fqdn: jabber.starz0r.com

loglevel: 5

default_db: sql
sm_db_type: sql
new_sql_schema: true

certfiles:
    - /home/ejabberd/acme/live/starz0r.com/privkey.pem
    - /home/ejabberd/acme/live/starz0r.com/fullchain.pem

c2s_ciphers: "HIGH+kEDH:HIGH+kEECDH:HIGH:!PSK:!SRP:!3DES:!aNULL"
s2s_ciphers: "HIGH+kEDH:HIGH+kEECDH:HIGH:!PSK:!SRP:!3DES:!aNULL"

s2s_use_starttls: optional

listen:
    -
        port: 5222
        module: ejabberd_c2s
        access: c2s
        shaper: c2s_shaper
        max_stanza_size: 262144
        use_proxy_protocol: true
        starttls: true
        starttls_required: false
    -
        port: 5223
        module: ejabberd_c2s
        access: c2s
        shaper: c2s_shaper
        max_stanza_size: 262144
        use_proxy_protocol: true
        starttls: true
        starttls_required: true
    -
        port: 5269
        module: ejabberd_s2s_in
        shaper: s2s_shaper
        max_stanza_size: 131072
        use_proxy_protocol: true
    -
        port: 5270
        module: ejabberd_s2s_in
        shaper: s2s_shaper
        max_stanza_size: 131072
        use_proxy_protocol: true
        tls: true
    -
        port: 5280
        module: ejabberd_http
        tls: false
        register: false
        request_handlers:
            /admin: ejabberd_web_admin
            /ws: ejabberd_http_ws
            /bosh: mod_bosh

shaper:
    normal: 1000
    fast: 50000

outgoing_s2s_families:
    - ipv4
    - ipv6
outgoing_s2s_timeout: 10000

host_config:
    starz0r.com:
        # Database
        sql_type: pgsql
        sql_server: ${database_host}
        sql_ssl: true
        sql_port: 25060
        sql_pool_size: 1
        sql_database: ejabberd
        sql_username: jabber
        sql_password: ${database_pass}
        # Authentication
        auth_method: ldap
        ldap_servers:
            - ldaps.starz0r.com
        ldap_uids:
            - uid
        ldap_encrypt: tls
        ldap_tls_verify: soft
        ldap_tls_depth: 1
        ldap_port: 30003
        ldap_rootdn: "cn=Admin,dc=starz0r,dc=com"
        ldap_base: "ou=users,dc=starz0r,dc=com"
        ldap_filter: "(objectClass=inetOrgPerson)"
        ldap_password: ${ldap_pass}

# Enabled Modules
modules:
    mod_adhoc: {}
    mod_admin_extra: {}
    mod_announce:
        access: announce
    # mod_avatar: {}
    mod_blocking: {}
    mod_bosh: {}
    mod_caps: {}
    mod_carboncopy: {}
    mod_client_state: {}
    mod_configure: {}
    mod_disco: {}
    mod_echo: {}
    mod_last: {}
    mod_mam:
        assume_mam_usage: true
        default: always
        request_activates_archiving: true
    mod_muc:
        access:
            - allow
        access_admin:
            - allow: admin
        access_create: muc_create
        access_persistent: muc_create
        default_room_options:
            mam: true
            persistent: true
            public: false
            public_list: false
        history_size: 50
        max_users: 100
    mod_muc_admin: {}
    mod_offline:
        access_max_user_messages: max_user_offline_messages
    mod_ping: {}
    mod_pres_counter:
        count: 5
        interval: 60
    mod_privacy: {}
    mod_private: {}
    mod_pubsub:
        access_createnode: pubsub_createnode
        plugins:
            - "flat"
            - "pep"
        force_node_config:
            "eu.siacs.conversations.axolotl.*":
                access_model: open
            "storage:bookmarks":
                access_model: whitelist
    mod_push: {}
    mod_push_keepalive: {}
    mod_s2s_dialback: {}
    mod_roster:
        versioning: true
    mod_shared_roster: {}
    mod_sic: {}
    mod_stream_mgmt:
        resend_on_timeout: if_offline
    mod_vcard:
        search: false
    mod_vcard_xupdate: {}
    mod_version:
        show_os: true

# Access Rules
acl:
    admin:
        user:
            - "starz0r": "starz0r.com"

access_rules:
    local:
        - allow: local
    c2s:
        - allow
    muc_create:
        - allow: admin
    pubsub_createnode:
        - allow: local
    configure:
        - allow: admin

shaper_rules:
    max_user_offline_messages:
        - 32768: admin
        - 16384
